pipeline:
    name: Eval
    identifier: Eval
    allowStageExecutions: false
    projectIdentifier: Deploy
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy Service
              identifier: Deploy_Service
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: Evaluation
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: Eval
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: Personal_GH
                                                    gitFetchType: Branch
                                                    paths:
                                                        - manifests
                                                    branch: main
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: DockerHub
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: qa
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: Personal
                              namespace: qa
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
